# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Leef
tagline:          Blog
url:              http://blog.leef.io
paginate:         1
baseurl:          
author:
  name:           Leef
  url:            https://twitter.com/teamleef
  email:          hello@leef.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
